spring.application.name=security-app
server.port=8443
server.ssl.enabled=true

# Server keystore
server.ssl.key-store=classpath:security/server-keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=server

# Server truststore
server.ssl.trust-store=classpath:security/server-truststore.p12
server.ssl.trust-store-password=changeit
server.ssl.trust-store-type=PKCS12

# Require client certificate
server.ssl.client-auth=need
